server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    gateway:
      routes:
        - id: short-link-admin
          uri: lb://short-link-admin/api/short-link/admin/**
          predicates:
            - Path=/api/short-link/admin/**
          filters:
            - PreserveHostHeader # 防止host被修改为localhost
        - id: short-link-project
          uri: lb://short-link-project/api/short-link/**
          predicates:
            -  Path=/api/short-link/**
          filters:
            - PreserveHostHeader # 防止host被修改为localhost
        - id: short-link-restoreUrl
          uri: lb://short-link-project/**
          predicates:
            - Path=/**
          filters:
            - PreserveHostHeader # 防止host被修改为localhost
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG