---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-link-project-deployment
  labels:
    app: short-link-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: short-link-project
  template:
    metadata:
      name: short-link-project
      labels:
        app: short-link-project
    spec:
      containers:
        - name: short-link-project
          image: pepsiwyl920/short-link-project:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          volumeMounts:
            - mountPath: /app/logs
              name: logs
      volumes:
        - name: logs
          nfs:
            # NFS 服务 地址 选取k8s-node1
            server: 172.16.255.11
            # NFS 服务 共享目录 下 /app/logs
            path: /nfs/data/app/logs
      restartPolicy: Always
---
# service
apiVersion: v1
kind: Service
metadata:
  name: short-link-project-service
  labels:
    app: short-link-project
spec:
  selector:
    app: short-link-project
  type: NodePort
  ports:
    - name: short-link-project
      protocol: TCP
      port: 80
      targetPort: 8001
      nodePort: 30001
---