dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://mysql:3306/link?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

rules:
  - !SHARDING
    tables:
      t_link:
        actualDataNodes: ds_0.t_link_${0..15}
        tableStrategy:
          standard:
            shardingColumn: gid
            shardingAlgorithmName: link_table_hash_mod
      t_link_goto:
        actualDataNodes: ds_0.t_link_goto_${0..15}
        tableStrategy:
          standard:
            shardingColumn: full_short_url
            shardingAlgorithmName: link_goto_table_hash_mod
      t_link_stats_today:
        actualDataNodes: ds_0.t_link_stats_today_${0..15}
        tableStrategy:
          standard:
            shardingColumn: gid
            shardingAlgorithmName: link_stats_today_hash_mod
      t_link_access_stats:
        actualDataNodes: ds_0.t_link_access_stats_${0..15}
        tableStrategy:
          standard:
            shardingColumn: gid
            shardingAlgorithmName: link_access_stats_hash_mod
      t_link_locale_stats:
        actualDataNodes: ds_0.t_link_locale_stats_${0..15}
        tableStrategy:
          standard:
            shardingColumn: gid
            shardingAlgorithmName: link_locale_stats_hash_mod
      t_link_browser_stats:
        actualDataNodes: ds_0.t_link_browser_stats_${0..15}
        tableStrategy:
          standard:
            shardingColumn: gid
            shardingAlgorithmName: link_browser_stats_hash_mod
      t_link_os_stats:
        actualDataNodes: ds_0.t_link_os_stats_${0..15}
        tableStrategy:
          standard:
            shardingColumn: gid
            shardingAlgorithmName: link_os_stats_hash_mod
      t_link_device_stats:
        actualDataNodes: ds_0.t_link_device_stats_${0..15}
        tableStrategy:
          standard:
            shardingColumn: gid
            shardingAlgorithmName: link_device_stats_hash_mod
      t_link_network_stats:
        actualDataNodes: ds_0.t_link_network_stats_${0..15}
        tableStrategy:
          standard:
            shardingColumn: gid
            shardingAlgorithmName: link_network_stats_hash_mod
      t_link_access_logs:
        actualDataNodes: ds_0.t_link_access_logs_${0..15}
        tableStrategy:
          standard:
            shardingColumn: gid
            shardingAlgorithmName: link_access_logs_hash_mod
    bindingTables:
      - t_link, t_link_stats_today
    shardingAlgorithms:
      link_table_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16
      link_goto_table_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16
      link_stats_today_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16
      link_locale_stats_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16
      link_access_stats_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16
      link_browser_stats_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16
      link_os_stats_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16
      link_device_stats_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16
      link_network_stats_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16
      link_access_logs_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16
props:
  sql-show: true